# Generated by Django 3.2.25 on 2025-05-19 09:09

import Bable.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0006_auto_20250518_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjacentBodyCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_keyword', models.CharField(default='', max_length=66)),
                ('right_keyword', models.CharField(default='', max_length=66)),
                ('appearances_in_body_text', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BodyCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(default='', max_length=66)),
                ('appearances_in_body_text', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DoubleDoubleAdjacentBodyCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leftmost_keyword', models.CharField(default='', max_length=66)),
                ('left_keyword', models.CharField(default='', max_length=66)),
                ('right_keyword', models.CharField(default='', max_length=66)),
                ('rightmost_keyword', models.CharField(default='', max_length=66)),
                ('appearances_in_body_text', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DoubleLeftAdjacentBodyCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leftmost_keyword', models.CharField(default='', max_length=66)),
                ('left_keyword', models.CharField(default='', max_length=66)),
                ('right_keyword', models.CharField(default='', max_length=66)),
                ('appearances_in_body_text', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DoubleRightAdjacentBodyCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_keyword', models.CharField(default='', max_length=66)),
                ('right_keyword', models.CharField(default='', max_length=66)),
                ('rightmost_keyword', models.CharField(default='', max_length=66)),
                ('appearances_in_body_text', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DuoDuoBodyCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leftmost_keyword', models.CharField(default='', max_length=66)),
                ('left_keyword', models.CharField(default='', max_length=66)),
                ('right_keyword', models.CharField(default='', max_length=66)),
                ('rightmost_keyword', models.CharField(default='', max_length=66)),
                ('appearances_in_body_text', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_word', models.CharField(default='', max_length=66)),
            ],
        ),
        migrations.CreateModel(
            name='OneTripleBodyCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_keyword', models.CharField(default='', max_length=66)),
                ('rightleft', models.CharField(default='', max_length=66)),
                ('rightmiddle_keyword', models.CharField(default='', max_length=66)),
                ('rightmost_keyword', models.CharField(default='', max_length=66)),
                ('appearances_in_body_text', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SpacelessAdjacentBodyCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_keyword', models.CharField(default='', max_length=66)),
                ('right_keyword', models.CharField(default='', max_length=66)),
                ('appearances_in_body_text', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SpacelessQuatroBodyCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leftmost_keyword', models.CharField(default='', max_length=66)),
                ('left_keyword', models.CharField(default='', max_length=66)),
                ('right_keyword', models.CharField(default='', max_length=66)),
                ('rightmost_keyword', models.CharField(default='', max_length=66)),
                ('appearances_in_body_text', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SubFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_id', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TripleAdjacentBodyCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_keyword', models.CharField(default='', max_length=66)),
                ('middle_keyword', models.CharField(default='', max_length=66)),
                ('right_keyword', models.CharField(default='', max_length=66)),
                ('appearances_in_body_text', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TripleOneBodyCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leftmost_keyword', models.CharField(default='', max_length=66)),
                ('leftmiddle_keyword', models.CharField(default='', max_length=66)),
                ('leftright_keyword', models.CharField(default='', max_length=66)),
                ('right_keyword', models.CharField(default='', max_length=66)),
                ('appearances_in_body_text', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TripleSpacelessAdjacentBodyCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_keyword', models.CharField(default='', max_length=66)),
                ('middle_keyword', models.CharField(default='', max_length=66)),
                ('right_keyword', models.CharField(default='', max_length=66)),
                ('appearances_in_body_text', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_number', models.IntegerField(default=201879266)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='anon',
            name='first_name',
            field=models.CharField(default='', max_length=66),
        ),
        migrations.AddField(
            model_name='anon',
            name='last_name',
            field=models.CharField(default='', max_length=66),
        ),
        migrations.AddField(
            model_name='anon',
            name='password',
            field=models.CharField(default='', max_length=66),
        ),
        migrations.AddField(
            model_name='anon',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[Bable.models.validate_phone_number]),
        ),
        migrations.AddField(
            model_name='anon',
            name='user_name',
            field=models.CharField(default='', max_length=66, unique=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='dislikes',
            field=models.ManyToManyField(default=None, related_name='comment_dislikes', to='Bable.Author'),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(default=None, related_name='comment_likes', to='Bable.Author'),
        ),
        migrations.AlterField(
            model_name='page_density',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='sentence',
            field=models.TextField(default='', max_length=14400),
        ),
        migrations.CreateModel(
            name='ZipfsLawStatSignature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('four_of_one', models.ManyToManyField(default=None, to='Bable.SpacelessQuatroBodyCounter')),
                ('one_by_one', models.ManyToManyField(default=None, related_name='one_by_one', to='Bable.AdjacentBodyCounter')),
                ('one_by_one_by_one', models.ManyToManyField(default=None, to='Bable.TripleAdjacentBodyCounter')),
                ('one_by_one_by_one_by_one', models.ManyToManyField(default=None, to='Bable.DoubleDoubleAdjacentBodyCounter')),
                ('one_by_three', models.ManyToManyField(default=None, to='Bable.OneTripleBodyCounter')),
                ('one_of_one', models.ManyToManyField(default=None, to='Bable.BodyCounter')),
                ('one_skip_five_by_one', models.ManyToManyField(default=None, related_name='one_skip_five_by_one', to='Bable.AdjacentBodyCounter')),
                ('one_skip_five_by_two', models.ManyToManyField(default=None, related_name='one_skip_five_by_two', to='Bable.DoubleRightAdjacentBodyCounter')),
                ('one_skip_four_by_one', models.ManyToManyField(default=None, related_name='one_skip_four_by_one', to='Bable.AdjacentBodyCounter')),
                ('one_skip_four_by_two', models.ManyToManyField(default=None, related_name='one_skip_four_by_two', to='Bable.DoubleRightAdjacentBodyCounter')),
                ('one_skip_one_by_one', models.ManyToManyField(default=None, related_name='one_skip_one_by_one', to='Bable.AdjacentBodyCounter')),
                ('one_skip_one_by_two', models.ManyToManyField(default=None, related_name='one_skip_one_by_two', to='Bable.DoubleRightAdjacentBodyCounter')),
                ('one_skip_three_by_one', models.ManyToManyField(default=None, related_name='one_skip_three_by_one', to='Bable.AdjacentBodyCounter')),
                ('one_skip_three_by_two', models.ManyToManyField(default=None, related_name='one_skip_three_by_two', to='Bable.DoubleRightAdjacentBodyCounter')),
                ('one_skip_two_by_one', models.ManyToManyField(default=None, related_name='one_skip_two_by_one', to='Bable.AdjacentBodyCounter')),
                ('one_skip_two_by_two', models.ManyToManyField(default=None, related_name='one_skip_two_by_two', to='Bable.DoubleRightAdjacentBodyCounter')),
                ('three_by_one', models.ManyToManyField(default=None, to='Bable.TripleOneBodyCounter')),
                ('three_of_one', models.ManyToManyField(default=None, to='Bable.TripleSpacelessAdjacentBodyCounter')),
                ('two_by_two', models.ManyToManyField(default=None, to='Bable.DuoDuoBodyCounter')),
                ('two_of_one', models.ManyToManyField(default=None, related_name='two_of_one', to='Bable.SpacelessAdjacentBodyCounter')),
                ('two_skip_five_by_one', models.ManyToManyField(default=None, related_name='two_skip_five_by_one', to='Bable.DoubleLeftAdjacentBodyCounter')),
                ('two_skip_four_by_one', models.ManyToManyField(default=None, related_name='two_skip_four_by_one', to='Bable.DoubleLeftAdjacentBodyCounter')),
                ('two_skip_one_by_one', models.ManyToManyField(default=None, related_name='two_skip_one_by_one', to='Bable.DoubleLeftAdjacentBodyCounter')),
                ('two_skip_three_by_one', models.ManyToManyField(default=None, related_name='two_skip_three_by_one', to='Bable.DoubleLeftAdjacentBodyCounter')),
                ('two_skip_two_by_one', models.ManyToManyField(default=None, related_name='two_skip_two_by_one', to='Bable.DoubleLeftAdjacentBodyCounter')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(default='Topic Name', max_length=66)),
                ('privacy_settings', models.IntegerField(default=0)),
                ('exact_match', models.CharField(default='', max_length=66)),
                ('date_range_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_range_end', models.DateTimeField(default=django.utils.timezone.now)),
                ('active_admins', models.ManyToManyField(default=None, to='Bable.Author')),
                ('key_words_to_exclude', models.ManyToManyField(default=None, related_name='key_words_to_exclude', to='Bable.Keyword')),
                ('key_words_to_include', models.ManyToManyField(default=None, related_name='key_words_to_include', to='Bable.Keyword')),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Folder Name', max_length=66)),
                ('order', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Organisation', 'Organisation')], default='Public', max_length=66)),
                ('collaborators', models.ManyToManyField(default=None, to='Bable.Author')),
                ('comments', models.ManyToManyField(default=None, to='Bable.Comment')),
                ('sub_folders', models.ManyToManyField(default=None, to='Bable.SubFolder')),
            ],
        ),
        migrations.CreateModel(
            name='CollaborationWorkspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folders', models.ManyToManyField(default=None, to='Bable.Folder')),
            ],
        ),
        migrations.AddField(
            model_name='anon',
            name='email_verify',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_verify', to='Bable.verificationnumbers'),
        ),
        migrations.AddField(
            model_name='anon',
            name='phone_verify',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_verify', to='Bable.verificationnumbers'),
        ),
    ]
