# Generated by Django 3.2.25 on 2025-05-24 05:45

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0007_auto_20250519_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipfsApproximateDifferenceDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(default='', max_length=267)),
                ('significance', models.BooleanField(default=False)),
                ('year', models.IntegerField(default=2025)),
                ('month', models.IntegerField(default=1)),
                ('day', models.IntegerField(default=1)),
                ('one_of_one', models.FloatField(default=0.0)),
                ('one_by_one', models.FloatField(default=0.0)),
                ('two_of_one', models.FloatField(default=0.0)),
                ('one_by_one_by_one', models.FloatField(default=0.0)),
                ('one_skip_one_by_one', models.FloatField(default=0.0)),
                ('one_skip_two_by_one', models.FloatField(default=0.0)),
                ('one_skip_three_by_one', models.FloatField(default=0.0)),
                ('one_skip_four_by_one', models.FloatField(default=0.0)),
                ('one_skip_five_by_one', models.FloatField(default=0.0)),
                ('two_skip_one_by_one', models.FloatField(default=0.0)),
                ('two_skip_two_by_one', models.FloatField(default=0.0)),
                ('two_skip_three_by_one', models.FloatField(default=0.0)),
                ('two_skip_four_by_one', models.FloatField(default=0.0)),
                ('two_skip_five_by_one', models.FloatField(default=0.0)),
                ('one_skip_one_by_two', models.FloatField(default=0.0)),
                ('one_skip_two_by_two', models.FloatField(default=0.0)),
                ('one_skip_three_by_two', models.FloatField(default=0.0)),
                ('one_skip_four_by_two', models.FloatField(default=0.0)),
                ('one_skip_five_by_two', models.FloatField(default=0.0)),
                ('two_skip_one_by_two', models.FloatField(default=0.0)),
                ('two_skip_two_by_two', models.FloatField(default=0.0)),
                ('two_skip_three_by_two', models.FloatField(default=0.0)),
                ('two_skip_four_by_two', models.FloatField(default=0.0)),
                ('two_skip_five_by_two', models.FloatField(default=0.0)),
                ('three_of_one', models.FloatField(default=0.0)),
                ('one_by_one_by_one_by_one', models.FloatField(default=0.0)),
                ('two_by_two', models.FloatField(default=0.0)),
                ('four_of_one', models.FloatField(default=0.0)),
                ('three_by_one', models.FloatField(default=0.0)),
                ('one_by_three', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='zipfslawstatsignature',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='Bable.zipfslawstatsignature'),
        ),
        migrations.AddField(
            model_name='comment_edit',
            name='zipfslawstatsignature',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='Bable.zipfslawstatsignature'),
        ),
        migrations.AddField(
            model_name='edit',
            name='zipfslawstatsignature',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='Bable.zipfslawstatsignature'),
        ),
        migrations.AddField(
            model_name='post',
            name='zipfslawstatsignature',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='Bable.zipfslawstatsignature'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='zipfslawstatsignature',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='Bable.zipfslawstatsignature'),
        ),
        migrations.AddField(
            model_name='sentence_edit',
            name='zipfslawstatsignature',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='Bable.zipfslawstatsignature'),
        ),
        migrations.AddField(
            model_name='zipfslawstatsignature',
            name='body',
            field=models.TextField(default='', max_length=144000),
        ),
        migrations.AddField(
            model_name='zipfslawstatsignature',
            name='two_skip_five_by_two',
            field=models.ManyToManyField(default=None, related_name='two_skip_five_by_two', to='Bable.DuoDuoBodyCounter'),
        ),
        migrations.AddField(
            model_name='zipfslawstatsignature',
            name='two_skip_four_by_two',
            field=models.ManyToManyField(default=None, related_name='two_skip_four_by_two', to='Bable.DuoDuoBodyCounter'),
        ),
        migrations.AddField(
            model_name='zipfslawstatsignature',
            name='two_skip_one_by_two',
            field=models.ManyToManyField(default=None, related_name='two_skip_one_by_two', to='Bable.DuoDuoBodyCounter'),
        ),
        migrations.AddField(
            model_name='zipfslawstatsignature',
            name='two_skip_three_by_two',
            field=models.ManyToManyField(default=None, related_name='two_skip_three_by_two', to='Bable.DuoDuoBodyCounter'),
        ),
        migrations.AddField(
            model_name='zipfslawstatsignature',
            name='two_skip_two_by_two',
            field=models.ManyToManyField(default=None, related_name='two_skip_two_by_two', to='Bable.DuoDuoBodyCounter'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='Bable.author'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='has_viewed',
            field=models.ManyToManyField(default=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='Bable.author'), related_name='comments_has_viewed', to='Bable.Author'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='Bable.comment'),
        ),
        migrations.AlterField(
            model_name='comment_edit',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='Bable.author'),
        ),
        migrations.AlterField(
            model_name='verificationnumbers',
            name='verification_number',
            field=models.IntegerField(default=365725721),
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_heading', models.CharField(default='', max_length=66)),
                ('heading_count', models.IntegerField(default=0)),
                ('recommendation', models.TextField(default='', max_length=1440)),
                ('post_id', models.IntegerField(default=0)),
                ('comment_id', models.IntegerField(default=0)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='Bable.author')),
                ('zipfslawstatsignature', models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='Bable.zipfslawstatsignature')),
            ],
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_heading', models.CharField(default='', max_length=66)),
                ('heading_count', models.IntegerField(default=0)),
                ('insight', models.TextField(default='', max_length=1440)),
                ('post_id', models.IntegerField(default=0)),
                ('comment_id', models.IntegerField(default=0)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='Bable.author')),
                ('zipfslawstatsignature', models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='Bable.zipfslawstatsignature')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='insights',
            field=models.ManyToManyField(default=None, to='Bable.Insight'),
        ),
        migrations.AddField(
            model_name='comment',
            name='recommendations',
            field=models.ManyToManyField(default=None, to='Bable.Recommendation'),
        ),
        migrations.AddField(
            model_name='comment_edit',
            name='insights',
            field=models.ManyToManyField(default=None, to='Bable.Insight'),
        ),
        migrations.AddField(
            model_name='comment_edit',
            name='recommendations',
            field=models.ManyToManyField(default=None, to='Bable.Recommendation'),
        ),
        migrations.AddField(
            model_name='edit',
            name='insights',
            field=models.ManyToManyField(default=None, to='Bable.Insight'),
        ),
        migrations.AddField(
            model_name='edit',
            name='recommendations',
            field=models.ManyToManyField(default=None, to='Bable.Recommendation'),
        ),
        migrations.AddField(
            model_name='post',
            name='insights',
            field=models.ManyToManyField(default=None, to='Bable.Insight'),
        ),
        migrations.AddField(
            model_name='post',
            name='recommendations',
            field=models.ManyToManyField(default=None, to='Bable.Recommendation'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='insights',
            field=models.ManyToManyField(default=None, to='Bable.Insight'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='recommendations',
            field=models.ManyToManyField(default=None, to='Bable.Recommendation'),
        ),
        migrations.AddField(
            model_name='sentence_edit',
            name='insights',
            field=models.ManyToManyField(default=None, to='Bable.Insight'),
        ),
        migrations.AddField(
            model_name='sentence_edit',
            name='recommendations',
            field=models.ManyToManyField(default=None, to='Bable.Recommendation'),
        ),
        migrations.AddField(
            model_name='zipfslawstatsignature',
            name='zipfs_law_difference_day',
            field=models.ManyToManyField(default=None, related_name='zipfs_law_difference', to='Bable.ZipfsApproximateDifferenceDay'),
        ),
        migrations.AddField(
            model_name='zipfslawstatsignature',
            name='zipfs_law_difference_day_significance',
            field=models.ManyToManyField(default=None, related_name='zipfs_law_difference_significance', to='Bable.ZipfsApproximateDifferenceDay'),
        ),
        migrations.AddField(
            model_name='zipfslawstatsignature',
            name='zipfs_law_difference_week',
            field=models.ManyToManyField(default=None, related_name='zipfs_law_week_difference', to='Bable.ZipfsApproximateDifferenceDay'),
        ),
        migrations.AddField(
            model_name='zipfslawstatsignature',
            name='zipfs_law_difference_week_significance',
            field=models.ManyToManyField(default=None, related_name='zipfs_law_week_difference_significance', to='Bable.ZipfsApproximateDifferenceDay'),
        ),
        migrations.AddField(
            model_name='zipfslawstatsignature',
            name='zipfs_law_difference_year',
            field=models.ManyToManyField(default=None, related_name='zipfs_law_year_difference', to='Bable.ZipfsApproximateDifferenceDay'),
        ),
        migrations.AddField(
            model_name='zipfslawstatsignature',
            name='zipfs_law_difference_year_significance',
            field=models.ManyToManyField(default=None, related_name='zipfs_law_year_difference_significance', to='Bable.ZipfsApproximateDifferenceDay'),
        ),
        migrations.AddField(
            model_name='zipfslawstatsignature',
            name='zipfs_law_sefl_difference_day_significance',
            field=models.ManyToManyField(default=None, related_name='zipfs_law_self_difference_significance', to='Bable.ZipfsApproximateDifferenceDay'),
        ),
        migrations.AddField(
            model_name='zipfslawstatsignature',
            name='zipfs_law_self_difference_day',
            field=models.ManyToManyField(default=None, related_name='zipfs_law_self_difference', to='Bable.ZipfsApproximateDifferenceDay'),
        ),
        migrations.AddField(
            model_name='zipfslawstatsignature',
            name='zipfs_law_self_difference_week',
            field=models.ManyToManyField(default=None, related_name='zipfs_law_self_week_difference', to='Bable.ZipfsApproximateDifferenceDay'),
        ),
        migrations.AddField(
            model_name='zipfslawstatsignature',
            name='zipfs_law_self_difference_week_significance',
            field=models.ManyToManyField(default=None, related_name='zipfs_law_self_week_difference_significance', to='Bable.ZipfsApproximateDifferenceDay'),
        ),
        migrations.AddField(
            model_name='zipfslawstatsignature',
            name='zipfs_law_self_difference_year',
            field=models.ManyToManyField(default=None, related_name='zipfs_law_self_year_difference', to='Bable.ZipfsApproximateDifferenceDay'),
        ),
        migrations.AddField(
            model_name='zipfslawstatsignature',
            name='zipfs_law_self_difference_year_significance',
            field=models.ManyToManyField(default=None, related_name='zipfs_law_self_year_difference_significance', to='Bable.ZipfsApproximateDifferenceDay'),
        ),
        migrations.AddField(
            model_name='zipfslawstatsignature',
            name='zipfs_law_signature',
            field=models.ManyToManyField(default=None, related_name='zipfs_law_signature', to='Bable.ZipfsApproximateDifferenceDay'),
        ),
    ]
