# Generated by Django 3.2.25 on 2025-05-24 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0009_auto_20250524_0846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zipfslawstatsignature',
            old_name='zipfs_law_sefl_difference_day_significance',
            new_name='zipfs_law_self_difference_day_significance',
        ),
        migrations.AddField(
            model_name='zipfsapproximatedifferenceday',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Bable.author'),
        ),
        migrations.AddField(
            model_name='zipfslawstatsignature',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Bable.author'),
        ),
        migrations.AddField(
            model_name='zipfslawstatsignature',
            name='ip_address',
            field=models.CharField(default='1.1.1.1', max_length=15),
        ),
        migrations.AddField(
            model_name='zipfslawstatsignature',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='zipfslawstatsignature',
            name='lng',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='verificationnumbers',
            name='verification_number',
            field=models.IntegerField(default=887043874),
        ),
    ]
