# Generated by Django 3.2.25 on 2025-05-24 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0010_auto_20250524_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zipfslawstatsignature',
            name='zipfs_law_signature',
        ),
        migrations.AddField(
            model_name='post',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='zipfsapproximatedifferenceday',
            name='lat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zipfsapproximatedifferenceday',
            name='lng',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zipfsapproximatedifferenceday',
            name='one_sum',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='verificationnumbers',
            name='verification_number',
            field=models.IntegerField(default=212105619),
        ),
    ]
