# Generated by Django 3.2.25 on 2025-05-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0011_auto_20250524_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='zipfslawstatsignature',
            name='day',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='zipfslawstatsignature',
            name='month',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='zipfslawstatsignature',
            name='year',
            field=models.IntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='verificationnumbers',
            name='verification_number',
            field=models.IntegerField(default=46778523),
        ),
    ]
