# Generated by Django 3.2.25 on 2025-05-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0012_auto_20250524_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='zipfslawstatsignature',
            name='one_sum',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='verificationnumbers',
            name='verification_number',
            field=models.IntegerField(default=311550994),
        ),
    ]
