# Generated by Django 5.2.2 on 2025-06-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0013_auto_20250524_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationnumbers',
            name='verification_number',
            field=models.IntegerField(default=155988619),
        ),
    ]
