# Generated by Django 5.2.2 on 2025-06-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0014_alter_verificationnumbers_verification_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationnumbers',
            name='verification_number',
            field=models.IntegerField(default=915663367),
        ),
    ]
