# Generated by Django 5.2.2 on 2025-06-07 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0015_alter_verificationnumbers_verification_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationnumbers',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Bable.author'),
        ),
        migrations.AlterField(
            model_name='verificationnumbers',
            name='verification_number',
            field=models.IntegerField(default=373485058),
        ),
    ]
