# Generated by Django 5.2.2 on 2025-06-07 14:48

import Bable.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0016_verificationnumbers_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationnumbers',
            name='verification_number',
            field=models.CharField(default=815143824, max_length=9, validators=[Bable.models.validate_verification_number]),
        ),
    ]
