# Generated by Django 5.2.2 on 2025-06-07 16:45

import Bable.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0017_alter_verificationnumbers_verification_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationnumbers',
            name='verification_number',
            field=models.CharField(default=335134918, max_length=9, validators=[Bable.models.validate_verification_number]),
        ),
    ]
